blacklist = ["scratch", "temp", "default"]

sort_order = ["config", "tmux", "zoxide"]

[[session]]
name = "Alchemy"
path = "~/Work/Alchemy"
startup_command = "nvim"
windows = ["review", "testing", "terminal"]

[[session]]
name = "Deployment"
path = "~/Work/vps"
startup_command = "nvim"
windows = ["terminal"]

[[session]]
name = "Infrastructure"
path = "~/Work/gcp-infrastructure"
startup_command = "nvim"
windows = ["terminal"]

[[session]]
name = "Talos"
path = "~/Work/cluster"
startup_command = "nvim"
windows = ["terminal"]

[[window]]
name = "alchemy"
path = "~/Work/Alchemy"
startup_script = "nvim"

[[window]]
name = "review"
path = "~/Work/alchemy-review/"
startup_script = "nvim"

[[window]]
name = "testing"
path = "~/Work/testing"
startup_script = "nvim"

[[window]]
name = "infra"
path = "~/Work/gcp-infrastructure"
startup_script = "nvim"

[[window]]
name = "deploy"
path = "~/Work/vps"
startup_script = "nvim"

[[window]]
name = "code"
startup_script = "nvim"

[[window]]
name = "terminal"
