blacklist = ["scratch", "temp", "default"]

sort_order = ["config", "tmux", "zoxide"]

[[session]]
name = "Alchemy"
path = "~/work/Alchemy"
startup_command = "nvim"
windows = ["review", "testing", "terminal"]

[[session]]
name = "Deployment"
path = "~/work/vps"
startup_command = "nvim"
windows = ["terminal"]

[[session]]
name = "Infrastructure"
path = "~/work/gcp-infrastructure"
startup_command = "nvim"
windows = ["terminal"]

[[session]]
name = "Monitoring"
path = "~/work/monitoring"
startup_command = "nvim"
windows = ["terminal"]

[[session]]
name = "Talos"
path = "~/work/talos"
startup_command = "nvim"
windows = ["terminal"]

[[window]]
name = "alchemy"
path = "~/work/Alchemy"
startup_script = "nvim"

[[window]]
name = "review"
path = "~/work/alchemy-review/"
startup_script = "nvim"

[[window]]
name = "testing"
path = "~/work/testing"
startup_script = "nvim"

[[window]]
name = "infra"
path = "~/work/gcp-infrastructure"
startup_script = "nvim"

[[window]]
name = "deploy"
path = "~/work/vps"
startup_script = "nvim"

[[window]]
name = "monitoring"
path = "~/work/monitoring"
startup_script = "nvim"

[[window]]
name = "code"
startup_script = "nvim"

[[window]]
name = "terminal"
