# Set color support
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:Tc"

# -- Settings
# Start windows and panes on 1
set -g base-index 1
setw -g pane-base-index 1
set -g mode-keys vi
set -g status-keys vi
set -g mouse on
set -g focus-events on
set -s escape-time 0
set -g display-time 4000
set -g status-interval 5
setw -g aggressive-resize on
set -g detach-on-destroy off  # don't exit from tmux when closing a session
set-option -g default-shell /bin/zsh

# -- Keybinds
# Leader
unbind C-b
set -g prefix `
bind ` send-prefix
bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt

# General
bind R source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"
# Change so in copy mode (leader+[) enter line select with v only, and toggle block select with Ctrl+v
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Open splits and panes in same directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# -- Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'alexwforsythe/tmux-which-key'

# Vim navigator conf
set -g @plugin 'christoomey/vim-tmux-navigator'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
set -g @vim_navigator_mapping_left "C-Left"
set -g @vim_navigator_mapping_right "C-Right"
set -g @vim_navigator_mapping_up "C-Up"
set -g @vim_navigator_mapping_down "C-Down"
set -g @vim_navigator_mapping_prev ""
set -g @powerkit_pane_border_lines "single"

# Sesh
bind-key "t" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

# THEME
set -g @plugin 'fabioluciano/tmux-powerkit'
set -g @powerkit_theme "tokyo-night"
set -g @powerkit_separator_style "slant"
set -g @powerkit_edge_separator_style "slant"
set -g @powerkit_status_position "bottom"
set -g @powerkit_plugins ""
set -g @powerkit_session_icon "auto"
set -g @powerkit_window_index_style "text"
set -g @powerkit_pane_border_lines "heavy"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
