# ---  Window constraints and rules for placement/size

# --- Float/tiled
# Float/tiled constraints
windowrulev2 = float, class:^vivaldi-stable$, initialTitle:^Bitwarden - Vivaldi$

# --- Workspace locations
windowrulev2 = workspace 5 silent, class:^.*-music\.youtube.*$
# windowrulev2 = workspace 6 silent, class:^discord$
# windowrulev2 = workspace 6 silent, class:^(TeamSpeak 3)$
