# ---  Window constraints and rules for placement/size
windowrule {
  name = windowrule-1
  max_size = 2560 1440
  match:class = (.*)
}

# --- Float/tiled
# Float/tiled constraints
windowrule {
  name = windowrule-2
  float = on
  match:class = ^vivaldi-stable$
  match:initial_title = ^Bitwarden - Vivaldi$
}

# --- Workspace locations
windowrule {
  name = windowrule-3
  workspace = 5 silent
  match:class = ^.*-music\.youtube.*$
}

# Btop fix
windowrule {
  name = btop-size
  match:class = org.omarchy.btop
  float = on
  min_size = 1000 1000
}
# windowrulev2 = workspace 6 silent, class:^discord$
# windowrulev2 = workspace 6 silent, class:^(TeamSpeak 3)$
