require("config.defaults")
require("config.envs")
require("config.monitors")
require("config.input")
require("config.looknfeel")
require("config.binds")
require("config.windowrules")
require("config.autostart")
