# Application bindings
$terminal = uwsm app -- $TERMINAL
# $browser = omarchy-launch-browser
$browser = vivaldi

# Syntax: SUPER + MOD, Description, exec, command. For omarchy-launch-or-focus-webapp it takes a regex before exec


# --- Launch commands
bindd = SUPER, return, Terminal, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER, N, Editor, exec, omarchy-launch-editor
bindd = SUPER, I, Docker, exec, $terminal -e lazydocker
bindd = SUPER, slash, Passwords, exec, uwsm app -- bitwarden-desktop
bindd = SUPER, A, Claude, exec, omarchy-launch-or-focus-webapp Claude "https://claude.com"
bindd = SUPER, S, Slack, exec, omarchy-launch-or-focus-webapp Slack "https://app.slack.com/client/T4WV23X5X/C078XNMBW13"
bindd = SUPER, C, Calendar, exec, omarchy-launch-or-focus-webapp Calendar "https://calendar.google.com/calendar"
bindd = SUPER, E, Email, exec, omarchy-launch-or-focus-webapp Gmail "https://mail.google.com/mail/"
bindd = SUPER, O, Obsidian, exec, omarchy-launch-or-focus "^obsidian$" "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"

# System
bindd = SUPER, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER, T, Activity, exec, $terminal -e btop

# Music
bindd = SUPER, M, YoutubeMusic, exec, omarchy-launch-or-focus-webapp "Youtube Music" "https://music.youtube.com"
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify

# Socials
bindd = SUPER, D, Discord, exec, omarchy-launch-or-focus discord

# --- Window management
bindde = SUPER ALT, left, Resize window width, resizeactive, -30 0
bindde = SUPER ALT, right, Resize window width, resizeactive, 30 0
bindde = SUPER ALT, up, Resize window height, resizeactive, 0 -30
bindde = SUPER ALT, down, Resize window height, resizeactive, 0 30

# --- Pass commands
# Mute/unmute TS
bind = SHIFT, F2, pass, class:^(TeamSpeak 3)$
bind = SHIFT, F1, pass, class:^(TeamSpeak 3)$
bind = SHIFT, F1, pass, class:^(TeamSpeak 3)$

# Media keys
bind = ,XF86AudioNext, pass, class:^.*-music\.youtube.*$
bind = ,XF86AudioPause, pass, class:^.*-music\.youtube.*$
bind = ,XF86AudioPlay, pass, class:^.*-music\.youtube.*$


# Left behind examples from default config
# bindd = SUPER, G, Signal, exec, omarchy-launch-or-focus signal ""
# bindd = SUPER SHIFT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
# bindd = SUPER, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
# bindd = SUPER SHIFT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
# bindd = SUPER ALT, G, Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
# bindd = SUPER, X, X, exec, omarchy-launch-webapp "https://x.com/"
# bindd = SUPER SHIFT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
