# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$terminal = uwsm app -- $TERMINAL
# $browser = omarchy-launch-browser
$browser = vivaldi-stable

# Syntax: SUPER + MOD, Description, exec, command. For omarchy-launch-or-focus-webapp it takes a regex before exec

# --- Shortcut actions
unbind = SUPER, L
bindd = SUPER, L, Lock computer, exec, hyprlock

# --- Launch commands
bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER SHIFT, B, Browser, exec, $browser --incognito
bindd = SUPER, slash, Passwords, exec, uwsm app -- bitwarden-desktop
bindd = SUPER, A, Claude, exec, omarchy-launch-or-focus-webapp Claude "https://claude.ai"
bindd = SUPER SHIFT, S, Slack, exec, omarchy-launch-or-focus-webapp Slack "https://app.slack.com/client/T4WV23X5X/C078XNMBW13"
bindd = SUPER SHIFT, I, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-or-focus-webapp Calendar "https://calendar.google.com/calendar"
bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-or-focus-webapp Gmail "https://mail.google.com/mail/"
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus "^obsidian$" "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"

# System tools
bindd = SUPER SHIFT, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop

# Music
bindd = SUPER, M, Youtube Music, exec, omarchy-launch-or-focus-webapp "youtube" "https://music.youtube.com"
bindd = SUPER SHIFT, M, Spotify, exec, omarchy-launch-or-focus spotify

# Socials
bindd = SUPER, D, Discord, exec, omarchy-launch-or-focus discord

# --- Window management
bindde = SUPER ALT, left, Resize window width, resizeactive, -30 0
bindde = SUPER ALT, right, Resize window width, resizeactive, 30 0
bindde = SUPER ALT, up, Resize window height, resizeactive, 0 -30
bindde = SUPER ALT, down, Resize window height, resizeactive, 0 30

# --- Pass commands
# Mute/unmute TS
bind = SHIFT, F2, pass, class:^(TeamSpeak 3)$
bind = SHIFT, F1, pass, class:^(TeamSpeak 3)$
bind = SHIFT, F1, pass, class:^(TeamSpeak 3)$

# Media keys
bind = ,XF86AudioNext, pass, class:^.*-music\.youtube.*$
bind = ,XF86AudioPause, pass, class:^.*-music\.youtube.*$
bind = ,XF86AudioPlay, pass, class:^.*-music\.youtube.*$


# --- Unbind Omarchy defaults
# Toggle groups
# unbind = SUPER, G, Toggle window grouping, togglegroup
# unbind = SUPER ALT, G, Move active window out of group, moveoutofgroup

# Join groups
unbind = SUPER ALT, LEFT, Move window to group on left, moveintogroup, l
unbind = SUPER ALT, RIGHT, Move window to group on right, moveintogroup, r
unbind = SUPER ALT, UP, Move window to group on top, moveintogroup, u
unbind = SUPER ALT, DOWN, Move window to group on bottom, moveintogroup, d

# Navigate a single set of grouped windows
unbind = SUPER ALT, TAB, Next window in group, changegroupactive, f
unbind = SUPER ALT SHIFT, TAB, Previous window in group, changegroupactive, b
unbind = SUPER, TAB, Next workspace, workspace, +1
bindd = SUPER, TAB, Next window in group, changegroupactive, f

# Activate window in a group by number
# unbind = SUPER ALT, 1, Switch to group window 1, changegroupactive, 1
# unbind = SUPER ALT, 2, Switch to group window 2, changegroupactive, 2
# unbind = SUPER ALT, 3, Switch to group window 3, changegroupactive, 3
# unbind = SUPER ALT, 4, Switch to group window 4, changegroupactive, 4
# unbind = SUPER ALT, 5, Switch to group window 5, changegroupactive, 5

# Fullwidth
# unbind = SUPER ALT, F


# Left behind examples from default config
# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
# bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
