# Add general aliases
alias ipython="ipython3"
alias clip="xclip -selection clipboard"
alias bat="/usr/bin/batcat"
alias n="nvim-open"
alias balias="~/.bashrc.d/bash_aliases"
alias bashrc="~/.bashrc"
alias sbat="sudo batcat"
alias ll="ls -l"
alias aenv="export \$(grep -v '^#' .env | xargs)"
alias denv="unset \$(grep -v '^#' .env | sed -E 's/(.*)=.*/\1/' | xargs)"

# Folder aliases for fast navigation

# Add git aliases
alias gadd="git add"
alias gcmt="git commit"
alias gst="git status"
alias lgt="lazygit"

# Add python alias
alias python="python3"
alias ve="python3 -m venv ./venv"
alias va="source ./venv/bin/activate"
alias da="deactivate"

# Minicube alias
alias kube="kubectl"
alias mkube="minikube kubectl --"

# Add nvim aliases
alias nconf="nvim-open ~/.config/nvim/init.lua"
alias bconf="nvim ~/.bashrc"
alias aconf="nvim ~/.bashrc.d/bash_aliases"
alias iconf="nvim ~/.config/i3/config"
alias sconf="nvim ~/.config/starship.toml"
alias ctodo="nvim ~/notes/TODO"
alias todo="clear && cat ~/notes/TODO"

# Add docker aliases
alias ldk="lazydocker"
