# Add general aliases
alias ipython="ipython3"
alias clip="xclip -selection clipboard"
alias bat="/usr/bin/batcat"
alias n="nvim"
alias balias="~/.bashrc.d/bash_aliases"
alias bashrc="~/.bashrc"
alias 'sbat'="sudo batcat"
alias ll="ls -l"
alias setenv="export $(grep -v '^#' .env | xargs)"
alias unsetenv="unset $(grep -v '^#' .env | sed -E 's/(.*)=.*/\1/' | xargs)"

# Add git aliases
alias gadd="git add"
alias gcmt="git commit"
alias gst="git status"
alias lgt="lazygit"

# Add python alias
alias python="python3"
alias ve="python3 -m venv ./venv"
alias va="source ./venv/bin/activate"

# Add nvim aliases
alias nconf="nvim ~/.config/nvim/init.lua"
alias bconf="nvim ~/.bashrc"
alias aconf="nvim ~/.bashrc.d/bash_aliases"
alias iconf="nvim ~/.config/i3/config"
alias todo="nvim ~/notes/TODO"

# Add docker aliases
alias ldk="lazydocker"
