# Extra autostart processes
# exec-once = uwsm app -- my-service

exec-once = xrandr --output DP-1 --primary

exec-once = [workspace 6 silent] uwsm app -- teamspeak3
exec-once = [workspace 6 silent] uwsm app -- discord

# Move mouse to workspace 1
exec-once = hyprctl dispatch workspace 1
