# Extra autostart processes
# exec-once = uwsm app -- my-service

exec-once = xrandr --output DP-1 --primary
exec-once = teamspeak3
exec-once = discord
exec-once = hyprctl dispatch resizewindowpixel 0 -300, class:^discord$
# Move mouse to workspace 1
exec-once = hyprctl dispatch workspace 1
