# Extra autostart processes
# exec-once = uwsm app -- my-service

# Set display
exec-once = xrandr --output DP-1 --primary

# Move mouse to workspace 1
exec-once = hyprctl dispatch workspace 1

# Launch programs, remember uwsm prefix, important
exec-once = [workspace 6 silent] uwsm app -- teamspeak3 # Modify TS3 .desktop file for uwsm too
exec-once = [workspace 6 silent] uwsm app -- discord

