# Window constraints and rules for placement/size

# Location constraints
windowrulev2 = workspace 5, class:^.*-music\.youtube.*$
windowrulev2 = workspace 6, class:^discord$
windowrulev2 = workspace 6, class:^(TeamSpeak 3)$
windowrulev2 = workspace 2, class:^steam$

# Float/tiled constraints

# Game settings
windowrulev2 = workspace 3, class:^steam_app.*$
windowrule = content game, class:^steam_app.*$
windowrule = fullscreen, content:game
windowrule = immediate, content:game
