# ---  Window constraints and rules for placement/size
# Tags
windowrulev2 = tag +game, class:^steam_app_[0-9]+$
windowrulev2 = tag +game, initialTitle:^World of Warcraft$, xwayland:1

# --- Game settings
windowrulev2 = workspace 3 silent, tag:game
windowrulev2 = immediate, renderunfocused, tag:game

# --- Float/tiled
# Float/tiled constraints
windowrulev2 = float, class:^vivaldi-stable$, initialTitle:^Bitwarden - Vivaldi$
windowrulev2 = float, initialClass:^Bitwarden$

# --- Workspace locations
windowrulev2 = workspace 5 silent, class:^.*-music\.youtube.*$
windowrulev2 = workspace 6 silent, class:^discord$
windowrulev2 = workspace 6 silent, class:^(TeamSpeak 3)$
windowrulev2 = workspace 2 silent, noinitialfocus, class:^steam$
windowrulev2 = workspace 2 silent, noinitialfocus, class:^steam_app_default$, initialTitle:^Battle\.net.*$
# Below for stupid taskbar icon
windowrulev2 = workspace 2 silent, noinitialfocus, class:^steam_app_default$, xwayland:1, initialTitle:^$
