# ---  Window constraints and rules for placement/size
# Tags
windowrule {
  name = windowrule-1
  tag = +game
  match:class = ^steam_app_[0-9]+$
}

windowrule {
  name = windowrule-2
  tag = +game
  match:class = ^stellaris$
}

windowrule {
  name = windowrule-3
  tag = +game
  match:initial_title = ^World of Warcraft$
  match:xwayland = 1
}


# --- Game settings
windowrule {
  name = windowrule-4
  workspace = 3 silent
  immediate = on
  render_unfocused = on
  match:tag = game
}


# --- Float/tiled
# Float/tiled constraints
windowrule {
  name = windowrule-5
  float = on
  match:class = ^vivaldi-stable$
  match:initial_title = ^Bitwarden - Vivaldi$
}

windowrule {
  name = windowrule-6
  float = on
  match:initial_class = ^Bitwarden$
}


# --- Workspace locations
windowrule {
  name = windowrule-7
  workspace = 5 silent
  match:class = ^.*-music\.youtube.*$
}

windowrule {
  name = windowrule-8
  workspace = 6 silent
  match:class = ^discord$
}

windowrule {
  name = windowrule-9
  workspace = 6 silent
  match:class = ^(TeamSpeak 3)$
}

windowrule {
  name = windowrule-10
  workspace = 2 silent
  no_initial_focus = on
  match:initial_class = ^(steam)$
}

windowrule {
  name = windowrule-11
  workspace = 2 silent
  no_initial_focus = on
  match:class = ^steam_app_default$
  match:initial_title = ^Battle\.net.*$
}

# Below for stupid taskbar icon
windowrule {
  name = windowrule-12
  workspace = 2 silent
  no_initial_focus = on
  match:class = ^steam_app_default$
  match:xwayland = 1
  match:initial_title = ^$
}

